language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
after_script:
  - "./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info"
