language: node_js
node_js:
  - 6
  - 7
  - 8
cache:
  directories:
    - node_modules
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - npm run styles
  - npm run flow
  - npm test -- --coverage
  - npm run build
after_script:
  - "./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info"
  - "./node_modules/.bin/coveralls < coverage/lcov.info"
  - greenkeeper-lockfile-upload
after_success:
  - bash <(curl -s https://codecov.io/bash)
