language: node_js
node_js:
  - 4
  - 6
  - 7
cache:
  directories:
    - node_modules
script:
  - npm run flow
  - npm test -- --coverage
after_script:
  - "./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info"
  - "./node_modules/.bin/coveralls < coverage/lcov.info"
after_success:
  - bash <(curl -s https://codecov.io/bash)
